#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & rofi & brightnessctl & dunst & $HOME/.config/polybar/launch.sh & picom --config ~/.config/picom/picom.conf.example &

bspc monitor eDP-1 -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#8ed1d0"
bspc config normal_border_color "#464e5e"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=off
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Termite:Ranger state=floating

feh --bg-center ~/Pictures/bg.png
xfsettingsd

